# fly.toml app configuration file generated for fpldraftwatchlist on 2023-08-01T21:28:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fpldraftwatchlist"
primary_region = "lhr"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
